openapi: 3.0.0
info:
  title: Physical AI & Humanoid Robotics Textbook - Authentication API
  description: API for user authentication and personalization features
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.physical-ai-textbook.com
    description: Production server

paths:
  /api/auth/register:
    post:
      summary: Register a new user
      description: Create a new user account with optional personalization profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - name
              properties:
                email:
                  type: string
                  format: email
                  description: User's email address
                password:
                  type: string
                  format: password
                  minLength: 8
                  description: User's password
                name:
                  type: string
                  description: User's full name
                background:
                  type: string
                  enum: [software, hardware, mixed, beginner]
                  description: User's technical background
                preferred_language:
                  type: string
                  default: en
                  description: User's preferred language (e.g., en, ur)
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  access_token:
                    type: string
                    description: JWT access token
                  token_type:
                    type: string
                    default: bearer
        '400':
          description: Bad request - invalid input or user already exists
        '500':
          description: Internal server error

  /api/auth/login:
    post:
      summary: User login
      description: Authenticate user and return access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: JWT access token
                  token_type:
                    type: string
                    default: bearer
        '401':
          description: Invalid credentials
        '500':
          description: Internal server error

  /api/auth/profile:
    get:
      summary: Get user profile
      description: Retrieve current user's profile information
      security:
        - BearerAuth: []
      responses:
        '200':
          description: User profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized - invalid or missing token
        '500':
          description: Internal server error
    put:
      summary: Update user profile
      description: Update current user's profile information
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Updated user name
                background:
                  type: string
                  enum: [software, hardware, mixed, beginner]
                  description: Updated technical background
                preferred_language:
                  type: string
                  description: Updated preferred language (e.g., en, ur)
                learning_pace:
                  type: string
                  enum: [fast, moderate, slow]
                  description: Updated learning pace preference
                interests:
                  type: array
                  items:
                    type: string
                  description: Updated list of robotics interests
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized - invalid or missing token
        '500':
          description: Internal server error

  /api/auth/personalization:
    get:
      summary: Get personalization profile
      description: Retrieve user's personalization settings and preferences
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Personalization profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonalizationProfile'
        '401':
          description: Unauthorized - invalid or missing token
        '404':
          description: Personalization profile not found
        '500':
          description: Internal server error
    put:
      summary: Update personalization profile
      description: Update user's personalization settings and preferences
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonalizationProfileUpdate'
      responses:
        '200':
          description: Personalization profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonalizationProfile'
        '401':
          description: Unauthorized - invalid or missing token
        '500':
          description: Internal server error

  /api/auth/translate:
    post:
      summary: Get content translation
      description: Retrieve translated content for the user's preferred language
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content_id
                - target_language
              properties:
                content_id:
                  type: string
                  format: uuid
                  description: ID of the content to translate
                target_language:
                  type: string
                  description: Target language code (e.g., ur for Urdu)
      responses:
        '200':
          description: Translated content retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  original_content:
                    type: string
                    description: Original content in source language
                  translated_content:
                    type: string
                    description: Translated content
                  language_code:
                    type: string
                    description: Target language code
                  status:
                    type: string
                    enum: [completed, pending, error]
        '401':
          description: Unauthorized - invalid or missing token
        '404':
          description: Content or translation not found
        '500':
          description: Internal server error

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        name:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        preferences:
          type: object
          description: User preferences and settings

    PersonalizationProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        background:
          type: string
          enum: [software, hardware, mixed, beginner]
        preferred_language:
          type: string
          default: en
        learning_pace:
          type: string
          enum: [fast, moderate, slow]
        interests:
          type: array
          items:
            type: string
        challenge_level:
          type: string
          enum: [beginner, intermediate, advanced]
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    PersonalizationProfileUpdate:
      type: object
      properties:
        background:
          type: string
          enum: [software, hardware, mixed, beginner]
        preferred_language:
          type: string
        learning_pace:
          type: string
          enum: [fast, moderate, slow]
        interests:
          type: array
          items:
            type: string
        challenge_level:
          type: string
          enum: [beginner, intermediate, advanced]